### ISSUE TITLE
Feature Request: Support for Multiple Connection Factories

### ISSUE THREAD

**Issue by davydotcom** [micronaut-projects/micronaut-rabbitmq#11]
It is a common use case to have a service that connects to multiple rabbitMQ servers (an example might be a cross region exchange vs. a local exchange.

**Comment by jameskleeh** [comment]
@davydotcom How would one determine which connection to use for each publisher/consumer?

**Comment by davydotcom** [comment]
One would typically specify a connection name or alias in the annotation for the listener. This is how we do it with ours...

For example... Our grails rabbitmq plugin queue listener annotation looks like this

```
	@com.bertram.rabbitmq.conf.Queue(name='applianceJobQueue', autoDelete=false, durable=true, exclusive=false, consumers=5, conAlias='main', autoStartup=true)
```

Note the conAlias attribute to specify the connection. This lack of support was always a problem in the official grails rabbitmq plugin and so we never used it as in large enterprises we had situations where we had seperate rabbit clusters in different regions or even we had a mirrored event exchange that dev/test/qa could listen on to get production like data for other testing.

**Comment by jameskleeh** [comment]
Completed by https://github.com/micronaut-projects/micronaut-rabbitmq/commit/40fa3c6fb4c929a692b7365dbd1962768acee645
