### ISSUE TITLE
Feature Request: Load Balance Connection Factory

### ISSUE THREAD

**Issue by davydotcom** [micronaut-projects/micronaut-rabbitmq#12]
The rabbitmq client supports a list of hosts instead of just a single host for client side load-balancing and fail-over. Add Support to Connection Factory (not mentioned in docs)

**Comment by davydotcom** [comment]
https://www.rabbitmq.com/api-guide.html#address-array

**Comment by jameskleeh** [comment]
Completed by https://github.com/micronaut-projects/micronaut-rabbitmq/commit/40fa3c6fb4c929a692b7365dbd1962768acee645
