### ISSUE TITLE
How to reconnect exclusive queue?

### ISSUE THREAD

**Issue by l0co** [micronaut-projects/micronaut-rabbitmq#153]
In my microservice app I have an exclusive rabbit queue with a consumer:

```java
@RabbitListener
public class RabbitConsumer {

	@Queue(value = "some-queue", exclusive = true)
	public void receive(
		@RabbitProperty("correlationId") String correlationId,
		@Header(Rabbit.HEADER_RETRIES) Integer retryCount,
		RabbitAcknowledgement ack,
		Envelope envelope,
		Object object
	) {
		// ...
	}

}
```

Now, if two instances of this microservice are run, one of them throws a `RabbitListenerException` with `ShutdownSignalException: channel error; protocol method: #method<channel.close>(reply-code=403, reply-text=ACCESS_REFUSED - queue 'some-queue' in vhost '/' in exclusive use, class-id=60, method-id=20)` cause, what is fair enough.

However, in microservices world my exclusive listener can be killed at any moment together with the service instance and I'm left with no consumers for that queue (unless another service instance will be created). So, I want to detect whether there're no listeners to the queue and try to restart listener bean if it's possible. Here is the simple conceptual implementation for this scenario"

```java
@RabbitListener
public class RabbitConsumer implements RabbitListenerExceptionHandler {

	boolean connected = true;

	public boolean isConnected() {
		return connected;
	}

	@Override
	public void handle(RabbitListenerException exception) {
		connected = false;
	}

	@Queue(value = "some-queue", exclusive = true)
	public void receive(
		@RabbitProperty("correlationId") String correlationId,
		@Header(Rabbit.HEADER_RETRIES) Integer retryCount,
		RabbitAcknowledgement ack,
		Envelope envelope,
		Object object
	) {
		// ...
	}

}
```

And the restarting bean concept (in kotlin):

```kotlin
@Singleton
class RabbitRestart(
    val advice: RabbitMQConsumerAdvice,
    val context: ApplicationContext,
) {

    @Scheduled(fixedRate = "30s")
    fun schedule() {

        val listeners = context.getBeansOfType(RabbitConsumer::class.java)

        if (listeners.size>0) {

            listeners.forEach { listener ->
                if (!listener.isConnected) {
                    logger.debug("LISTENER: {} not connected, destroying", listener)
                    // DO DESTROY THE LISTENER AND FORCE TO RECREATE IT
                } else {
                    logger.debug("LISTENER: {} connected", listeners)
                }
            }

        }

    }

}
```

Now, my question is what should I put into `DO DESTROY THE LISTENER AND FORCE TO RECREATE IT` to recreate listener bean and try to connect it again?

Also, do you have any reconnection policy for non-exclusive queues in case, for example, going down with rabbit broker?

**Comment by jameskleeh** [comment]
You would have to inject RabbitMQConsumerAdvice and call `process` passing in the bean definition and method in order to recreate the listener

Regarding the reconnection policy, that is solely handled by the RabbitMQ java library. Any options available there are available to be configured
