### ISSUE TITLE
Divergent default number of consumers

### ISSUE THREAD

**Issue by niclarcipretti** [micronaut-projects/micronaut-rabbitmq#16]
I've created two test projects (one using JDK and one using GraalVM). Both using the micronaut-rabbit dependency and having a rabbit consumer. Curiously, when I runned them, the JDK project created 1 consumer connnection but the GraalVM one created 2 consumer connections (same implementation in both of them).

I could´t find any doc on how to configure the number of parallel consumers. Is there any way to?

Shouldn't both create a single consumer connection by default too?

Any help would be very much appreciated.

Cheers

Nikao

**Comment by jameskleeh** [comment]
@niclarcipretti It's important to use the right terms here. This implementation utilizes a single connection per server configured. You're referring to the number of parallel consumers. The consumers operate on a thread pool, so the number of concurrent consume operations would be limited by the number of threads in the pool. That doesn't have anything to do with the actual number of consumers as far as I'm aware.

The behavior is documented here https://micronaut-projects.github.io/micronaut-rabbitmq/latest/guide/#consumerExecutor

As far as why there are 2 connections in GraalVM, I really don't know. Are you using the latest GraalVM release?
