### ISSUE TITLE
Support for RPC

### ISSUE THREAD

**Issue by ilopmar** [micronaut-projects/micronaut-rabbitmq#2]
Besides the support for standard RabbitMQ publish-subscribe pattern it would be good to support RPC-pattern.
More info:
- https://www.rabbitmq.com/tutorials/tutorial-six-java.html
- https://www.rabbitmq.com/tutorials/tutorial-six-spring-amqp.html

**Comment by jameskleeh** [comment]
For reference:
https://github.com/rabbitmq/rabbitmq-tutorials/blob/master/java/RPCClient.java
https://github.com/rabbitmq/rabbitmq-tutorials/blob/master/java/RPCServer.java
https://www.rabbitmq.com/direct-reply-to.html
