### ISSUE TITLE
Allow dynamic @Queue name

### ISSUE THREAD

**Issue by gahissy** [micronaut-projects/micronaut-rabbitmq#22]
It should be possible to use a property in Queue names for more flexibility.

https://github.com/micronaut-projects/micronaut-rabbitmq/blob/44e72380044b38b3a5871afa42255616fad8045b/rabbitmq/src/main/java/io/micronaut/configuration/rabbitmq/intercept/RabbitMQConsumerAdvice.java#L193

**Comment by gahissy** [comment]
It looks like this is already supported.

**Comment by stigmelling** [comment]
Any idea how to configure this?

**Comment by abedurftig** [comment]
Hey @gahissy, do you remember how to do this?
