### ISSUE TITLE
Messages not received with Micronaut 3.0-SNAPSHOT

### ISSUE THREAD

**Issue by ilopmar** [micronaut-projects/micronaut-rabbitmq#238]
When using latest Micronaut `3.0.0-SNAPSHOT`, the messages are not received by listeners (`@RabbitListener`). The same code works properly with 3.0.0-M1.

### Steps to Reproduce

- Publish to Maven Local the code in this module from `master` branch that already includes the `MessageMapping` fix: https://github.com/micronaut-projects/micronaut-rabbitmq/pull/237
- `git clone https://github.com/micronaut-graal-tests/micronaut-rabbitmq-graal` 
- `cd micronaut-rabbitmq-graal`
- `git checkout 3.0.x-listener-not-working`
- The branch is configured to force the version `2.5.1-SNAPSHOT` from mavenLocal.
- `docker run -it --rm -p 15672:15672 -p 5672:5672 rabbitmq:3.8.9-management-alpine`
- `./gradlew run`
- `curl localhost:8080/books-fireandforget/1491950358`
- `curl localhost:8080/analytics`

### Expected Behaviour

The last curl should return `[{"bookIsbn":"1491950358","count":1}]` and if you call the first curl more, the `count` in the response is increased.

It also happens running `curl -s localhost:8080/books-rpc` because that sends a RPC call and as the message is not consumed by the listener there is a timeout error.

### Actual Behaviour

It returns an empty json array (or you get a timeout sending the `books-rpc` request.

### Environment Information

- **Operating System**: Linux Mint 20.1
- **Micronaut Version:** 3.0.0-SNAPSHOT
- **JDK Version:** 8

**Comment by graemerocher** [comment]
This is a known issue due the missing `MessageMapping` annotation?

**Comment by graemerocher** [comment]
OH missed the first bullet

**Comment by ilopmar** [comment]
The same also happens also for MQTT module.

**Comment by graemerocher** [comment]
Perhaps `@Executable` needs to be added to the annotation. Strange that `@AliasFor` doesn't work

**Comment by jameskleeh** [comment]
@graemerocher The issue is here:

```
            methodStream.forEach(reference -> {
                List<Class<? extends Annotation>> annotations = reference.getAnnotationTypesByStereotype(Executable.class);
                annotations.forEach(annotation -> byAnnotation.compute(annotation, (ann, list) -> {
                    if (list == null) {
```

`reference.getAnnotationTypesByStereotype(Executable.class)` returns only `MessageMapping` thus the future call to find the processor fails:

```
 byAnnotation.forEach((annotationType, methods) ->
                    streamOfType(ExecutableMethodProcessor.class, Qualifiers.byTypeArguments(annotationType))
```

**Comment by graemerocher** [comment]
the latter change makes sense to me

**Comment by jameskleeh** [comment]
@graemerocher Do you agree that `@Queue` should be returned from `reference.getAnnotationTypesByStereotype(Executable.class);` ?

**Comment by graemerocher** [comment]
What happens if you add `@Executable` onto `@Queue` as a meta-annotation?
