### ISSUE TITLE
Are there plans to support non-blocking consumers in the rabbitmq library?

### ISSUE THREAD

**Issue by oscarfh** [micronaut-projects/micronaut-rabbitmq#240]
With the rabbitmq library, I can have non-blocking producers. My use case is very simple: I have a consumer that, upon receiving a message, will makes some http calls, so I want it to be non-blocking to make better usage of my resources.
As far as I can see in [RabbitMQConsumerAdvice](https://github.com/micronaut-projects/micronaut-rabbitmq/blob/55943b964959d643601e823fcf7054ab4949c7f0/rabbitmq/src/main/java/io/micronaut/rabbitmq/intercept/RabbitMQConsumerAdvice.java#L107) this is not possible yet.
Are there plans to do so, similarly to what we have in the [Kafka library](https://micronaut-projects.github.io/micronaut-kafka/latest/guide/#kafkaListenerMethods)?

**Comment by jameskleeh** [comment]
Is this in the case of RPC? I don't see any point otherwise

**Comment by oscarfh** [comment]
All my consumer does upon receiving a message is calling 3 different endpoints one after another. I thought I could improve resource utilization by making this whole chain reactive (so I would be able to consumer more then one message per thread).
As it turns out, this is not possible with the Kafka library due to a kafka client restriction (ack should be send by the same thread that received the message). I assume this is similar in rabbit, so I think we can close this ticket.

**Comment by jameskleeh** [comment]
See https://www.rabbitmq.com/api-guide.html#channel-threads

When manual acknowledgements are used, it is important to consider what thread does the acknowledgement. If it's different from the thread that received the delivery (e.g. Consumer#handleDelivery delegated delivery handling to a different thread), acknowledging with the multiple parameter set to true is unsafe and will result in double-acknowledgements, and therefore a channel-level protocol exception that closes the channel. Acknowledging a single message at a time can be safe.

So you should be OK as long as you are just acking a single message

**Comment by jameskleeh** [comment]
In either case though it wouldn't require a change on our end. You can inject the acknowledgement argument and call it from whatever thread is used to subscribe to the resulting flow

**Comment by oscarfh** [comment]
This is what I mean (Kafka specific): https://github.com/micronaut-projects/micronaut-kafka/issues/103#issuecomment-595996097
If I am not mistaken, if the consumer thread has to ACK the processing of the message, it cannot receive a new message, since it has a pending ACK, effectively blocking the thread. In this case we would not benefit from the reactive paradigm.
