### ISSUE TITLE
When there are accumulated messages in rabbitmq in micronaut, and the rabbimq consumer starts to work immediately when the project is started here, but because some things in the micronaut framework have not been initialized, an error is reported

### ISSUE THREAD

**Issue by chengna106** [micronaut-projects/micronaut-rabbitmq#247]
When there are accumulated messages in rabbitmq in micronaut, and the rabbimq consumer starts to work immediately when the project is started here, but because some things in the micronaut framework have not been initialized, an error is reported

**Comment by jameskleeh** [comment]
If you update this issue with more relevant information I'll reopen it
