### ISSUE TITLE
Consumer is not closed on application shutdown

### ISSUE THREAD

**Issue by agsgde** [micronaut-projects/micronaut-rabbitmq#298]
### Expected Behavior

If the application receives a SIGTERM, the consumers should finish processing the current message and then stop

### Actual Behaviour

The consumer continues consuming messages until the queue is empty.

From what I understand, when shutting down the application the cancel method in the RecoverableConsumerWrapper waits 500ms when there is currently more than one message being processed. During this timeout the consumer can consume more messages and the cancel method has to wait again. This cycle will continue until all messages that are currently in the queue are consumed.

If other things on which the consumer relies on are shut down before the consumer, this can lead to 1000s of failing consumed messages that all need to be requeued.

### Version

3.2.0

**Comment by kurtseebauer** [comment]
a similar question was asked here: https://stackoverflow.com/questions/68590404/how-to-programmatically-stop-rabbitlistener-in-micronaut
but no solution was found.

**Comment by kurtseebauer** [comment]
as an interim solution, is there any way to do a programmatic close of the Consumer on application shutdown?

**Comment by sbodvanski** [comment]
PR: https://github.com/micronaut-projects/micronaut-rabbitmq/pull/394
