### ISSUE TITLE
Split annotations package into rabbitmq-annotations module

### ISSUE THREAD

**Issue by graemerocher** [micronaut-projects/micronaut-rabbitmq#3]
If we ever need to add type element visitors or annotation mappers it is useful having a JAR with just the annotations to put on the `annotationProcessor` path.

I can imagine you may want compile time validation of return types etc.

We should be doing the same for all modules that introduce annotations in the future and probably should do the same for Kafka etc.

**Comment by jameskleeh** [comment]
@graemerocher What to do about the `@RabbitClient` annotation that has `@Type(RabbitMQIntroductionAdvice.class)` ? If only the annotations were moved the class isn't available. Is there a string based version?

**Comment by graemerocher** [comment]
Good point.. hmm let me give it some thought
