### ISSUE TITLE
Support consumer auto acknowledge mode

### ISSUE THREAD

**Issue by mahileeb** [micronaut-projects/micronaut-rabbitmq#325]
### Feature description

It would be great to be able to disable manual acknowledgement to improve performance of "fire and forget" type topics. We would need to be able to update this line

```
channel.basicConsume(queue, false, consumerTag, false, exclusive, arguments, consumer);
```
to pass true into the autoAck param and then make RabbitMQConsumerAdvice.process skip acknowledgement logic if auto-ack was enabled.

**Comment by sbodvanski** [comment]
PR: https://github.com/micronaut-projects/micronaut-rabbitmq/pull/395
