### ISSUE TITLE
Number of consumers should be configurable

### ISSUE THREAD

**Issue by oscarfh** [micronaut-projects/micronaut-rabbitmq#327]
### Expected Behavior

This ticket is an improvement over the solution found in https://github.com/micronaut-projects/micronaut-rabbitmq/issues/248

The number of consumers is something that should be configurable, that means, if I start with 10 consumers and my load increases, I should have both options: scaling horizontally (adding more replicas of my application) and increasing the number of consumers. I should not be forces to rebuild my application to increase/decrease the number of consumers.

### Actual Behaviour

The current implementation forces the user to have a hardcoded number of consumers, because the following expression does not work: `@Queue(numberOfConsumers = "${configured-number-of-consumers}")`, since the parameter is an int.

One cannot use the `@Value()` annotation because the field should be a constant (`static final` and should not be set in the constructor), otherwise the code does not compile. Therefore is not possible to expose this field to be configurable in any way.

### Steps To Reproduce

N/A

### Environment Information

JDK: 11
MN: 3.3.4

### Version

3.3.4

**Comment by oscarfh** [comment]
I created a PR with a simple solution (use String in the annotation and letting the parse happens in the consumer advice). This would solve the issue because then the syntax `${my-property}` could be used.

**Comment by relyativus** [comment]
Hey guys. Any updates on this one? I see open PR for quite a while https://github.com/micronaut-projects/micronaut-rabbitmq/pull/329. We would really love to use this capability. And as I understand, there should be follow-up PR that will support configuration property placeholder replacement.

**Comment by graemerocher** [comment]
@sbodvanski next one for you
