### ISSUE TITLE
Configure auto creation exchanges/queues via properties

### ISSUE THREAD

**Issue by witek1902** [micronaut-projects/micronaut-rabbitmq#4]
It's really useful if user can configure auto creation (on/off) exchanges/queues creation via properties.
It simplifies working in dev environments.

Using Java API directly is not good option to do this in my opinion (https://micronaut-projects.github.io/micronaut-rabbitmq/latest/guide/#initialization).

Based on discussion: https://twitter.com/wojtek_suwala/status/1096435776756297729 :)

**Comment by jameskleeh** [comment]
> Using Java API directly is not good option to do this in my opinion (https://micronaut-projects.github.io/micronaut-rabbitmq/latest/guide/#initialization).

@witek1902 I'm interested to hear why. Adding queue and exchange declarations to the AOP advice would complicate matters and would likely not be able to satisfy every use case. A simple bean that does the declarations up front is more performant, clear, and flexible compared to attempting to do so behind the scenes.

**Comment by witek1902** [comment]
@jameskleeh you are right. Configuration through annotation can be more complicated. It can introduce more evil than good.

But in dev environments auto creation exchanges/queues/bindings with default settings IMO could simplify and speed up working.

**Comment by jameskleeh** [comment]
@witek1902 You have called out the other issue.. "in dev environments". I don't think its reasonable for the application to have to know what the dev environment is. For that simple bean you can add a `@Requires` so it won't load under any conditions you like. I'm going to close this issue for now until someone comes up with some compelling reason why it's a good idea.
