### ISSUE TITLE
Migrate to new configuration ascidoc macro

### ISSUE THREAD

**Issue by wetted** [micronaut-projects/micronaut-rabbitmq#426]
### Issue description

Migrate to new configuration ascidoc macro

**Comment by alvarosanchez** [comment]
Dean, when you work on this, please have a look at the missing code samples snippets:

![image](https://user-images.githubusercontent.com/153880/215050466-d91185eb-385c-4f17-96ac-1c9b337af419.png)

**Comment by wetted** [comment]
The broken snippet links are addressed by #427
