### ISSUE TITLE
ChannelInitializer swallows exceptions during initilization

### ISSUE THREAD

**Issue by nik-lazer** [micronaut-projects/micronaut-rabbitmq#44]
https://github.com/micronaut-projects/micronaut-rabbitmq/blob/d1244973f9079c72755da4055aa58350536e7047/rabbitmq/src/main/java/io/micronaut/configuration/rabbitmq/connect/ChannelInitializer.java#L50

During testing my extension ChannelInitilizer I found out that in case of any exception they won't be handled at all and won't be even logged due to empty catch block:
![micronaut-rabbit](https://user-images.githubusercontent.com/1555606/66554936-7e49ee80-eb56-11e9-9ab6-a69e4f104716.JPG)
As a result, any issue during initialization of Rabbit infrostructure causes partly-built setup, which hard to detect and troubleshoot.

I did not elaborate on pull request, because I have not checked, how such exceptions should be usually handled in the framework. But I can provide a fix if the team would provide recommendations in this regard.

**Comment by jameskleeh** [comment]
So we should allow for an exception to be thrown here because that would interrupt the bean creation process which would prevent the entire RabbitMQ integration from working

The best thing to do here would be to log an error. A PR would be welcome
